namespace OfficeOpenXml.ConditionalFormatting.Contracts;

public interface IExcelConditionalFormattingBetween : IExcelConditionalFormattingRule, IExcelConditionalFormattingWithFormula2, IExcelConditionalFormattingWithFormula
{
}
